### ISSUE TITLE
bulma-tagsinput & bulma-accordion

### ISSUE THREAD

**Issue by crazedVic** [laravel-frontend-presets/bulma#12]
If you look at the documentation for these two specific controls, they require specific js files to function:

> The extension comes with a JavaScript implementation to expand / collapse accordion items. Don't forget to include it in your project.
> <script type="text/javascript" src="/node_modules/bulma-extensions/bulma-accordion/dist/bulma-accordion.min.js"></script>

And

> The extension comes with a JavaScript implementation to manage input tags type. Don't forget to include it in your project.
> <script type="text/javascript" src="/node_modules/bulma-extensions/bulma-tagsinput/dist/bulma-tagsinput.min.js"></script>

And I do see you have included them in bulma-extension.js:
_require('bulma-extensions/bulma-accordion/dist/bulma-accordion');
[...]
require('bulma-extensions/bulma-tagsinput/dist/bulma-tagsinput');_

I manually copied the javascript file /node_modules/bulma-extensions/bulma-tagsinput/dist/bulma-tagsinput.min.js over using mix.js and referenced it directly in <script> and the control worked fine.  But following your instructions on the default setup, these 2 specifically don't seem to work.

**Comment by crazedVic** [comment]
Actually more information, turns out that the welcome.blade.php that  the artisan command generated seems to not include the app.js script, to which you do append the following:
require('./bulma-extensions');

/bulma/blob/master/src/bulma-stubs/views/welcome.blade.php

So to get it working i just had to add this line:
<script type="text/javascript" src="{{  asset('js/app.js') }}"></script>

**Comment by m1guelpf** [comment]
ping @laravel-frontend-presets/bulma-preset Can you take a look at this?

**Comment by deeshrestha** [comment]
@crazedVic Can you be specific about the problem. 

Welcome page is a static page with static links so scripts are not included there intentionally. If you are testing on welcome page, yes you have to add the script manually.

It is assumed that your pages should extend the provided `layouts/app.blade.php` page that includes the script (or create your own layout and extend it).
