### ISSUE TITLE
Issue with bulma iconpicker extension

### ISSUE THREAD

**Issue by dmitrij-schmidt** [laravel-frontend-presets/bulma#14]
there's an issue with imports for iconPicker extension from Bulma Extensions. extension name is in camelCase, while in repo it's all lowercase

**current code**:
resources/assets/js/bulma-extensions.js
` require('bulma-extensions/bulma-iconpicker/dist/bulma-iconPicker');`
resources/assets/sass/bulma-extensions.sass
`@import "node_modules/bulma-extensions/bulma-iconpicker/dist/bulma-iconPicker.sass"`

**correct code**:
resources/assets/js/bulma-extensions.js
` require('bulma-extensions/bulma-iconpicker/dist/bulma-iconpicker');`
resources/assets/sass/bulma-extensions.sass
`@import "node_modules/bulma-extensions/bulma-iconpicker/dist/bulma-iconpicker.sass"`

**proof & source:**
https://github.com/Wikiki/bulma-iconpicker/tree/a695d934b491f03876b306aa00e663f8716b8644

**Comment by deeshrestha** [comment]
Updated in new release.
