### ISSUE TITLE
problems loading bulma css styles

### ISSUE THREAD

**Issue by arcanoix** [laravel-frontend-presets/bulma#15]
Hello everyone

I have a problem, then I do the **installation** steps of the package does **not load bulma styles**, did any of them happend?

![image](https://user-images.githubusercontent.com/6331999/37789261-cdd241b4-2dd9-11e8-91df-ce66324260cf.png)

**Comment by deeshrestha** [comment]
I have just tested. It is working fine. Try re-installing.
