### ISSUE TITLE
Bulma carousel

### ISSUE THREAD

**Issue by ShapesGraphicStudio** [laravel-frontend-presets/bulma#18]
Hi,
Did you manage to make Bulma carousel work with Laravel ?
I can't seem to get it done.
Regards

**Comment by deeshrestha** [comment]
Nope, seems all extensions that require javascript is broken. Waiting for another release.

**Comment by ShapesGraphicStudio** [comment]
Hi,
Thanks for the answer.
I do not know if it's Laravel best practice, but we got it fixed with Wikiki here:
https://github.com/Wikiki/bulma-carousel/issues/39

**Comment by deeshrestha** [comment]
Solved now

**Comment by ShapesGraphicStudio** [comment]
Hi, nice to read !
Could you please explain the best practice to add the carousel ?
