### ISSUE TITLE
Login page looks broken with Laravel 6.5+ and error during compilation

### ISSUE THREAD

**Issue by patlecat** [laravel-frontend-presets/bulma#29]
When using Laravel 6.5+ and the latest bulma-extension here then the login page looks broken visually. And during compilation it says it can't find some bootstrap stuff but i thought it was all replaced by bulma now?

And when is an update to Bulma 0.8 coming?

**Comment by codecapsules** [comment]
Exactly same error !!!
I resolve the problem with semicolon in sass but template broken ...

**Comment by codecapsules** [comment]
WARNING in ./resources/js/bootstrap.js
Module not found: Error: Can't resolve 'jquery' in '/Users/macpro/websites/laravel/test/resources/js'
 @ ./resources/js/bootstrap.js
 @ ./resources/js/app.js
 @ multi ./resources/js/app.js ./resources/sass/app.scss

ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):

				vertical-align: middle;
                         ^
      Semicolons aren't allowed in the indented syntax.
   ╷
86 │                 vertical-align: middle;
   │                                       ^
   ╵
  node_modules/bulma-extensions/bulma-slider/src/sass/index.sass 86:27  @import
  resources/sass/bulma-extensions.sass 16:9                             @import
  resources/sass/bulma.sass 20:9                                        @import

**Comment by codecapsules** [comment]
Finally i clean and refacto Page by Page and now 
i have a perfect Laravel 6+ / Bulma 0.0.8 own Auth System.
Not too complicated ^^
++

**Comment by patlecat** [comment]
@codecapsules Can you pls submit a PR with the fix? There's not much going on here and it could take months to be fixed.

**Comment by deeshrestha** [comment]
Have released new update v3.0.1 with bulma v0.8.0. Should solve the problem. 

However `bulma-extension` still pull older version of `bulma-slider` with semicolon bug. 

Do remove the semicolons from `node_modules/bulma-extensions/bulma-slider/src/sass/index.sass` at line 86 and 91 before running `npm run xxx`. Already reported the issue on `bulma-extension`
