### ISSUE TITLE
Remove bootstrap-sass reference

### ISSUE THREAD

**Issue by massiws** [laravel-frontend-presets/bulma#3]
When I compile assets with `npm run dev` I get this error:

> Laravel Mix
>
> Error: ./bootstrap
> Can't resolve 'bootstrap-sass' in /var/www/<my-app>/resources/assets/js

To fix this you need to comment out line 13 in `resources/assets/js/bootstrap.js`
```js
10 try {
11    window.$ = window.jQuery = require('jquery');
12 
13    // require('bootstrap-sass');
14 } catch (e) {}
```

**Comment by OwenMelbz** [comment]
Have you tried running `php artisan preset none` first to remove bootstrap?

**Comment by deeshrestha** [comment]
Usually  `preset none` is not required.
Try the new release. It should be fine now.

**Comment by massiws** [comment]
It works!
Thank you
