### ISSUE TITLE
Semicolons aren't allowed in the indented syntax.

### ISSUE THREAD

**Issue by avadis** [laravel-frontend-presets/bulma#30]
Hi,
node_modules/bulma-extensions/bulma-slider/src/sass/index.sass 86:27  
@import - Semicolons aren't allowed in the indented syntax.

![error](https://user-images.githubusercontent.com/5938630/72959672-5e1a0480-3dc0-11ea-87fa-78d1fad57f90.jpg)

**Comment by deeshrestha** [comment]
Please read latest release notes https://github.com/laravel-frontend-presets/bulma/releases/tag/v3.0.1
You have to fix that manually for now.

**Comment by superbiche** [comment]
@avadis you can use https://github.com/ds300/patch-package to make the change automatically applied upon next installs.
