### ISSUE TITLE
Install fails on fresh laravel 7.9.2 project

### ISSUE THREAD

**Issue by Msrgit** [laravel-frontend-presets/bulma#39]
Tried to install on fresh laravel 7.9.2.

mark@Linux-Mint:~/laravel/bulma$ php artisan --version
Laravel Framework 7.9.2
mark@Linux-Mint:~/laravel/bulma$ composer require laravel-frontend-presets/bulma
Using version ^3.0 for laravel-frontend-presets/bulma
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing laravel-frontend-presets/bulma (v3.0.3): Loading from cache
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   Error 

  Class 'Illuminate\Foundation\Console\PresetCommand' not found

  at vendor/laravel-frontend-presets/bulma/src/BulmaPresetServiceProvider.php:16
    12|      * @return void
    13|      */
    14|     public function boot()
    15|     {
  > 16|         PresetCommand::macro('bulma', function ($command) {
    17|             BulmaPreset::install(false);
    18|             $command->info('Bulma scaffolding installed successfully.');
    19|             $command->comment('Please run "npm install && npm run dev" to compile your fresh scaffolding.');
    20|         });

      +8 vendor frames 
  9   [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(LaravelFrontendPresets\BulmaPreset\BulmaPresetServiceProvider))

      +5 vendor frames 
  15  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json to its original content.

**Comment by yvesloy** [comment]
I've got the same issue!

**Comment by omiba** [comment]
#40 Should work.

**Comment by deeshrestha** [comment]
Merged #40
