### ISSUE TITLE
Problem with the pageloader extension

### ISSUE THREAD

**Issue by aocneanu** [laravel-frontend-presets/bulma#5]
1st, it's good to have a bulma preset for laravel.

When I do `npm run dev` with the pageloader extension enabled I get the following error:

```
resolve-url-loader cannot operate: CSS error
  /Users/user/code/project/resources/assets/sass/app.scss:11014:3: @keyframes missing '}'
  at error (/Users/user/code/project/node_modules/css/lib/parse/index.js:62:15)
```

**Comment by deeshrestha** [comment]
Its a warning showing up on latest laravel. Not sure it that is related to preset. May be laravel mix or webpack related.

**Comment by deeshrestha** [comment]
@aocneanu ya you are right, pageloader extension is causing this.

**Comment by Grummfy** [comment]
it has been fixed, just wait for the new release ;)

**Comment by deeshrestha** [comment]
Ya its fixed.
