### ISSUE TITLE
v1.6.8 requires bulma-extensions v0.5.3, but that version doen't exist on npm

### ISSUE THREAD

**Issue by tehuel** [laravel-frontend-presets/bulma#7]
I've just installed this preset, and when i ran `npm install` command, it gave me an error saying `"No matching version found for bulma-extensions@^0.5.3"`.

I then ran `npm show bulma-extensions versions`, and version numbers went up to 0.5.2.

Digging a little bit more: on bulma-extensions github repo [only the 0.5.2 release ](https://github.com/Wikiki/bulma-extensions/releases) appears. On npm it says [the latest of 21 releases is 0.5.2](https://www.npmjs.com/package/bulma-extensions)... BUT on [bulma-extensions documentation site](https://wikiki.github.io/), it shows the latest version as 0.5.3

**Comment by deeshrestha** [comment]
Just updated to latest versions.
